import LegalPage from '@/components/LegalPage';
export const metadata = { title: 'Terms & disclaimer | Astra-via' };
export default function Page() {
  return <LegalPage title="Terms & disclaimer" intro="The scope of this website, the limits of its content and your protected rights.">
    <article id="english" lang="en"><h2>English</h2>
      <h3>Website scope</h3><p>This public website is operated under the Astra-via name in Israel. It describes our approach to Result as a Service (RaaS), document review and a Web3 roadmap. It is informational material, not a checkout, investment offer, token sale or agreement to supply a particular service. Any paid product or service requires a separate agreement and applicable disclosures.</p>
      <h3>Current capability and future plans</h3><p>Roadmap descriptions are intentions and may change; they are not guarantees of delivery dates or functionality. Blockchain provenance and decentralized evidence storage are planned capabilities. Illustrations depict concepts rather than functioning product interfaces. We do not claim that Astra-via is independently certified as the first or only provider in a category.</p>
      <h3>Human review and professional advice</h3><p>AI-assisted outputs can contain omissions, unsupported inferences and errors. A quotation or source connection does not independently prove a statement true. Results require appropriate human review and verification. Website content does not replace legal, financial, medical or other professional advice and should not be the sole basis for a consequential decision. No particular business outcome is guaranteed.</p>
      <h3>Philosophy and artwork</h3><p>The Philosophy page contains editorial summaries and Astra-via’s interpretations of selected ideas. The thinkers’ views differ. Source links support further reading; they do not imply affiliation, endorsement or that the thinkers developed Astra-via’s process. Portraits are AI-generated artistic interpretations, not authenticated historical photographs. We welcome corrections through the contact address below.</p>
      <h3>Responsible use and intellectual property</h3><p>Use the site lawfully and do not disrupt its operation, attempt unauthorized access or misrepresent its content as an endorsed service or guarantee. Astra-via’s name, branding and site materials are subject to applicable intellectual property rights; third-party rights remain with their holders. Nothing here limits lawful quotation, fair use or other rights provided by law.</p>
      <h3>Availability and limitations of responsibility</h3><p>We aim to keep the site accurate and available, but material may become outdated and the site may be interrupted. To the extent permitted by applicable law, we do not give a contractual warranty of uninterrupted availability or completeness of informational content. Any claim concerning the site must be assessed under applicable law and the relevant circumstances.</p><p>Nothing on this website excludes responsibility that cannot lawfully be excluded, waives mandatory consumer, privacy or accessibility rights, or prevents a person from contacting a regulator or pursuing an available legal remedy. There is no blanket waiver of claims, compulsory arbitration or class-action waiver. These notices do not create rights to mislead users or avoid statutory obligations.</p>
      <h3>Applicable law and notices</h3><p>Israeli law applies subject to any mandatory rules that also apply; the competent court and available remedies are determined by applicable law. No exclusive forum is imposed by this notice. Updates apply to the website information from their publication and do not retroactively remove rights. Browsing alone is not acceptance of a separate paid-service contract.</p>
    </article>
    <article id="hebrew" lang="he" dir="rtl"><h2>עברית</h2>
      <h3>מטרת האתר</h3><p>אתר ציבורי זה מופעל בשם Astra-via בישראל. הוא מציג את הגישה שלנו ל-Result as a Service ‏(RaaS), לסקירת מסמכים ולתוכנית Web3. מדובר במידע, ולא באתר רכישה, הצעת השקעה, מכירת אסימונים או הסכם לאספקת שירות מסוים. מוצר או שירות בתשלום מחייבים הסכם נפרד וגילויים מתאימים.</p>
      <h3>יכולות קיימות ותוכניות עתידיות</h3><p>תיאור תוכנית הפיתוח מבטא כוונות שעשויות להשתנות ואינו הבטחה למועד או ליכולת. תיעוד מקור באמצעות בלוקצ׳יין ואחסון ראיות מבוזר הם יכולות מתוכננות. האיורים מציגים רעיונות ולא ממשקי מוצר פעילים. אין טענה לאישור עצמאי שלפיו Astra-via היא הספקית הראשונה או היחידה בתחום.</p>
      <h3>בדיקה אנושית וייעוץ מקצועי</h3><p>תוצרים בסיוע בינה מלאכותית עשויים לכלול השמטות, הסקות שאינן מבוססות ושגיאות. ציטוט או קישור למקור אינם מוכיחים כשלעצמם שטענה נכונה. נדרשות בדיקה אנושית ואימות מתאימים. תוכן האתר אינו מחליף ייעוץ משפטי, פיננסי, רפואי או מקצועי אחר ואין להסתמך עליו לבדו בהחלטה בעלת השלכות. אין הבטחה לתוצאה עסקית מסוימת.</p>
      <h3>פילוסופיה ואיורים</h3><p>עמוד הפילוסופיה כולל תקצירים עריכתיים ופרשנויות של Astra-via לרעיונות נבחרים. ההוגים אינם מסכימים בכל הנושאים. קישורי המקורות נועדו להמשך קריאה ואינם מעידים על קשר, חסות או פיתוח התהליך של Astra-via בידי ההוגים. הדיוקנאות הם פרשנות אמנותית שנוצרה בבינה מלאכותית ולא תצלומים היסטוריים מאומתים. ניתן לשלוח תיקונים לכתובת הקשר למטה.</p>
      <h3>שימוש אחראי וקניין רוחני</h3><p>יש להשתמש באתר כדין, לא לשבש את פעולתו, לא לנסות גישה בלתי מורשית ולא להציג את התוכן באופן מטעה כשירות מאושר או כהתחייבות. שם Astra-via, המיתוג וחומרי האתר כפופים לזכויות הקניין הרוחני החלות; זכויות צדדים שלישיים נשארות בידיהם. אין באמור כדי להגביל ציטוט כדין, שימוש הוגן או זכויות אחרות שבדין.</p>
      <h3>זמינות וגבולות אחריות</h3><p>אנו שואפים למידע מדויק ולזמינות, אך מידע עשוי להתיישן ופעולת האתר עשויה להיפסק. ככל שהדין מאפשר, לא ניתנת אחריות חוזית לזמינות רציפה או לשלמות תוכן המידע. טענה הנוגעת לאתר תיבחן לפי הדין החל והנסיבות.</p><p>אין באתר כדי לפטור מאחריות שלא ניתן לפטור ממנה כדין, לוותר על זכויות קוגנטיות של צרכנים, פרטיות או נגישות, או למנוע פנייה לרשות או מימוש סעד משפטי זמין. אין ויתור גורף על תביעות, בוררות כפויה או ויתור על הליך ייצוגי. ההודעות אינן מקנות זכות להטעות או להימנע מחובה שבדין.</p>
      <h3>דין חל ועדכונים</h3><p>הדין הישראלי חל בכפוף להוראות מחייבות נוספות ככל שהן חלות. הערכאה המוסמכת והסעדים נקבעים לפי הדין, ללא תניית שיפוט בלעדית בהודעה זו. עדכונים חלים על המידע באתר ממועד פרסומם ואינם שוללים זכויות למפרע. גלישה בלבד אינה קבלת חוזה נפרד לשירות בתשלום.</p>
    </article>
  </LegalPage>;
}
