import LegalPage from '@/components/LegalPage';
export const metadata = { title: 'Privacy & cookies | Astra-via' };
export default function Page() {
  return <LegalPage title="Privacy & cookies" intro="What this website processes, why it does so and how to contact us.">
    <article id="english" lang="en">
      <h2>English</h2>
      <h3>Who is responsible</h3><p>Astra-via, based in Israel, operates this public information website and determines the purposes of the website processing described here. Privacy enquiries and requests: <a href="mailto:support@astra-via.com">support@astra-via.com</a>.</p>
      <h3>Browsing and technical logs</h3><p>When you visit, Google Cloud infrastructure processes technical request information, which may include your IP address, browser or user agent, requested URL, timestamp and response status. We use this information to deliver the website, troubleshoot errors and protect its operation. Avoid putting personal or sensitive information in URLs. Hosting uses Cloud Run in the me-west1 region; Google’s network, support and service operations may involve processing outside Israel.</p>
      <h3>Cookies and browser storage</h3><p>This version does not set application cookies, use analytics or advertising trackers, or store data in localStorage or sessionStorage. The Reduce motion setting exists only in the page’s memory and resets on a fresh page load. The site reads your operating system’s reduced-motion preference to adapt its presentation. Artwork is served from the website and fonts use your device’s installed fonts; there are no embedded social feeds or videos.</p><p>There are no optional tracking cookies to accept or reject in this version. If optional analytics, advertising or third-party embeds are added, this notice and the necessary consent controls must be updated before they are enabled.</p>
      <h3>When you contact us</h3><p>If you choose to email Astra-via, we process your email address, any name you provide and the message contents to respond and handle your request. Providing these details is voluntary; there is no legal obligation to send an enquiry. Without a reply address or sufficient details, we may be unable to respond or resolve the request. Please avoid sending identity documents, confidential client files or other sensitive information unless specifically required through an appropriate channel.</p>
      <h3>Recipients and retention</h3><p>Relevant Astra-via personnel and service providers supporting hosting and email may process information for these purposes. Google Cloud is the hosting provider; email is handled through our email service infrastructure. We do not use this website to sell personal data or build advertising profiles. Information may be disclosed where required by law or necessary to handle legal proceedings, subject to applicable law.</p><p>The current Google Cloud default logging bucket retains request logs for 30 days. Correspondence is retained as needed to handle the enquiry, maintain necessary business records and meet applicable legal requirements; it should be deleted or de-identified when no longer needed. Longer retention may be necessary for a particular security incident or legal obligation. Service providers may maintain separate operational records under their applicable arrangements.</p>
      <h3>Your requests and choices</h3><p>Subject to Israeli law, you may request access to personal information held about you and correction of information that is inaccurate, incomplete, unclear or outdated. Contact the address above; we may need proportionate information to verify your identity. You can also ask about deletion or other applicable rights. We assess such requests under applicable law rather than promise that every request can be granted.</p>
      <h3>Security, external links and changes</h3><p>The site uses HTTPS and limits its public functions to informational browsing. No method of storage or transmission is completely secure. External source links lead to independent websites governed by their own privacy notices. Material changes to this website’s processing will be reflected in this notice. Browsing this page does not constitute blanket consent to unrelated processing.</p>
    </article>
    <article id="hebrew" lang="he" dir="rtl">
      <h2>עברית</h2><h3>האחראי לעיבוד וליצירת קשר</h3><p>Astra-via, הפועלת בישראל, מפעילה אתר מידע ציבורי זה וקובעת את מטרות העיבוד המתוארות כאן. לפניות ובקשות בנושא פרטיות: <a href="mailto:support@astra-via.com">support@astra-via.com</a>.</p>
      <h3>גלישה ולוגים טכניים</h3><p>בעת ביקור באתר תשתית Google Cloud מעבדת נתוני בקשה טכניים, שעשויים לכלול כתובת IP, סוג דפדפן, כתובת הדף המבוקש, מועד הבקשה וקוד תגובה. המטרות הן מסירת האתר, איתור תקלות ואבטחת פעולתו. אין לכלול מידע אישי או רגיש בכתובות URL. האירוח נעשה ב-Cloud Run באזור me-west1; פעילות הרשת, התמיכה והשירות של Google עשויה לכלול עיבוד מחוץ לישראל.</p>
      <h3>עוגיות ואחסון בדפדפן</h3><p>גרסה זו אינה מגדירה עוגיות יישום, אינה מפעילה כלי אנליטיקה או פרסום ואינה שומרת מידע ב-localStorage או ב-sessionStorage. הגדרת הפחתת התנועה נשמרת רק בזיכרון הדף ומתאפסת בטעינה חדשה. האתר קורא את העדפת הפחתת התנועה של מערכת ההפעלה. התמונות מוגשות מהאתר והגופנים הם גופנים המותקנים במכשיר שלכם ואין הטמעות של רשתות חברתיות או סרטונים.</p><p>אין בגרסה זו עוגיות מעקב אופציונליות שיש לאשר או לדחות. לפני הוספת כלי מעקב או הטמעות אופציונליות יש לעדכן את ההודעה ואת מנגנוני ההסכמה הנדרשים.</p>
      <h3>פנייה בדואר אלקטרוני</h3><p>אם תבחרו לפנות בדוא״ל, נעבד את כתובתכם, את השם אם מסרתם ואת תוכן ההודעה כדי להשיב ולטפל בפנייה. המסירה מרצון ואין חובה חוקית לשלוח פנייה. ללא כתובת לתשובה או פרטים מספיקים ייתכן שלא נוכל להשיב או לטפל בבקשה. אין לשלוח מסמכי זיהוי, חומר לקוחות חסוי או מידע רגיש אחר אלא אם התבקשו במפורש בערוץ מתאים.</p>
      <h3>מקבלי מידע ומשך השמירה</h3><p>אנשי Astra-via הרלוונטיים וספקי אירוח ודוא״ל עשויים לעבד מידע למטרות אלה. Google Cloud היא ספקית האירוח; הודעות עוברות דרך תשתית שירות הדוא״ל שלנו. האתר אינו משמש למכירת מידע אישי או ליצירת פרופילי פרסום. מידע עשוי להימסר כשנדרש לפי דין או לצורך טיפול בהליך משפטי, בכפוף לדין החל.</p><p>מאגר הלוגים ברירת המחדל הנוכחי של Google Cloud שומר לוגים של בקשות למשך 30 יום. תכתובות נשמרות ככל שנחוץ לטיפול בפנייה, לרישומים עסקיים נדרשים ולחובות שבדין, ויש למחוק או להפוך אותן לאנונימיות כשאין בהן עוד צורך. אירוע אבטחה או חובה משפטית מסוימים עשויים לחייב שמירה ממושכת יותר. ספקים עשויים להחזיק רישומים תפעוליים נפרדים לפי ההסדרים החלים עליהם.</p>
      <h3>זכויות ובקשות</h3><p>בכפוף לדין הישראלי ניתן לבקש לעיין במידע אישי המוחזק עליכם ולבקש תיקון מידע שאינו נכון, שלם, ברור או מעודכן. אפשר לפנות לכתובת לעיל; ייתכן שיידרשו פרטים מידתיים לאימות זהותכם. ניתן לפנות גם בנושא מחיקה או זכויות נוספות ככל שהן חלות. כל בקשה נבחנת לפי הדין, ואין הבטחה שכל בקשה תוכל להתקבל.</p>
      <h3>אבטחה, קישורים ושינויים</h3><p>האתר משתמש ב-HTTPS ומיועד לגלישה במידע בלבד. אין שיטת אחסון או העברה בטוחה לחלוטין. קישורים חיצוניים מפנים לאתרים עצמאיים שמדיניות הפרטיות שלהם חלה עליהם. שינויים מהותיים בעיבוד יעודכנו בהודעה זו. גלישה אינה הסכמה גורפת לעיבוד למטרות אחרות.</p>
    </article>
  </LegalPage>;
}
